#!/bin/bash
# Create dir for AppImages
mkdir -p ~/Applications

# Download
wget -q --show-progress -O ~/Applications/double_commander.AppImage https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-beta/AppImage/doublecmd-qt-latest-x86_64.AppImage
wget -q --show-progress -O ~/Applications/doublecmd.svg https://raw.githubusercontent.com/doublecmd/doublecmd/refs/heads/master/pixmaps/mainicon/dc_128.svg

# Make executable
chmod +x ~/Applications/double_commander.AppImage

echo "Double Commander downloaded into ~/Applications/double_commander.AppImage"

cat <<EOF > ~/.local/share/applications/doublecmd.desktop
[Desktop Entry]
Name=Double Commander
GenericName=File Manager
Comment=Double Commander is a cross platform open source file manager with two panels side by side.
Terminal=false
Icon=$HOME/Applications/doublecmd.svg
Exec=env QT_QPA_PLATFORMTHEME=qt5ct $HOME/Applications/double_commander.AppImage %f
Type=Application
MimeType=inode/directory;
Categories=Utility;FileTools;FileManager;
Keywords=folder;manager;explore;disk;filesystem;orthodox;copy;queue;queuing;operations;
EOF

echo "desktop entry created in ~/.local/share/applications/doublecmd.desktop"

update-desktop-database ~/.local/share/applications

echo "Install dependencies for qt5"
sudo apt install libqt5pas1 libqt5printsupport5t64
