#!/bin/bash

source ~/init/scripts/defaults.sh

ME=$(basename "${0}")
VERSION="v0.01"

function _default() {
	echo -e "${GREEN}identity${RESET}"
	echo -e "SSH Identity Utility (v.01). Use -h or --help param for help."
	echo -e ""
	echo -e "${YELLOW}USAGE:${RESET}"
	echo -e "    identity <SUBCOMMAND> <PARAMS>"
	echo -e "    ${GRAY}identity create user-abc abc@email.com${RESET}"
	echo -e ""
	echo -e "${YELLOW}SUBCOMMANDS:${RESET}"
	echo -e "    ${GREEN}create  ${RESET}Create new identity. PARAMS: <USERNAME> <EMAIL>"
	echo -e "    ${GREEN}list    ${RESET}List existing identities"
	echo -e ""
	_list
}

function _list() {
	echo -e "${YELLOW}AVAILABLE IDENTITIES:${RESET}"
	sed -n 's/.*Host /    /p' ~/.ssh/config
	echo -e ""
}

function _createUsage() {
	echo -e "${YELLOW}identity${RESET} > ${GREEN}create${RESET}"
	echo -e ""
	echo -e "${YELLOW}USAGE:${RESET}"
	echo -e "    identity create <USERNAME> <EMAIL>"
	echo -e ""
}

function _create() {
	# Validate
	case $2 in
		--help|-h)
			_createUsage
			exit 0
		;;
	esac
	# no params provided
	# identity already exists

	# Confirm
	echo -e "${YELLOW}identity${RESET} > ${GREEN}create${RESET}"
	echo -e ""
	echo -e "Creating new identity"
	echo -e "   USERNAME:   $2"
	echo -e "   EMAIL:      $3"
	echo -e ""
	echo -e "Looks ok? (Y/n)"
	echo -e ""
	echo -e "Identity created"
	exit 0
}

# Parse Inputs
case $1 in
	--help|-h)
		_default ;;
	list)
		_list ;;
	create)
		_create $@ ;;
	*)
		_default ; exit 0 ;;
esac

