#!/bin/bash

source ~/init/scripts/defaults.sh

ME=$(basename "${0}")
VERSION="v0.01"

function _default() {
	echo -e "${GREEN}identity${RESET}"
	echo -e "SSH Identity Utility (v.01). Use -h or --help param for help."
	echo -e ""
	echo -e "${YELLOW}USAGE:${RESET}"
	echo -e "    identity <SUBCOMMAND> <PARAMS>"
	echo -e "    ${GRAY}identity create user-abc abc@email.com${RESET}"
	echo -e ""
	echo -e "${YELLOW}SUBCOMMANDS:${RESET}"
	echo -e "    ${GREEN}create  ${RESET}Create new identity. PARAMS: <USERNAME> <EMAIL>"
	echo -e "    ${GREEN}list    ${RESET}List existing identities"
	echo -e "    ${GREEN}ssh     ${RESET}Create ssh key login"
	echo -e ""
	_list
}

function _list() {
	echo -e "${YELLOW}AVAILABLE IDENTITIES:${RESET}"
	sed -n 's/.*Host /    /p' ~/.ssh/config
	echo -e ""
}

function _ssh() {
	# TODO: This is not yet finished.
	# s add homebox user@192.168.0.1

	# Generates ssh key, copies it to target machine and logs in with the key.
	# So next time you just use `ssh name`
	# Single name for
	#  - machine
	#  - key file

	# Need to input
	#

	MY_SSH_EMAIL="my@email.com" # abc@def.ghi
	MY_SSH_KEY_NAME="machine_name" # id_ed25519_something
	MY_SSH_CONNECTION_NAME="machine_name" # something_github_connection
	MY_SSH_HOSTNAME="github.com"
	MY_SSH_USER="joe"

	# Generate SSH key
	mkdir -p ~/.ssh
	ssh-keygen -t ed25519 -C $MY_SSH_EMAIL -N "" -f "$HOME/.ssh/$MY_SSH_KEY_NAME"

	# Add new connection to ~/.ssh/config
	touch ~/.ssh/config
	chmod 600 ~/.ssh/config
	echo "\nHost "$MY_SSH_CONNECTION_NAME >> ~/.ssh/config
	echo "	HostName "$MY_SSH_HOSTNAME >> ~/.ssh/config
	echo "	User "$MY_SSH_USER >> ~/.ssh/config
	echo "	AddKeysToAgent yes" >> ~/.ssh/config
	echo "	IdentityFile ~/.ssh/"$MY_SSH_KEY_NAME >> ~/.ssh/config
	echo " " >> ~/.ssh/config

	ssh-copy-id -i "$HOME/.ssh/$MY_SSH_KEY_NAME" ${MY_SSH_USER}@${MY_SSH_HOSTNAME}
	ssh $MY_SSH_KEY_NAME
}

function _createUsage() {
	echo -e "${YELLOW}identity${RESET} > ${GREEN}create${RESET}"
	echo -e ""
	echo -e "${YELLOW}USAGE:${RESET}"
	echo -e "    identity create <USERNAME> <EMAIL>"
	echo -e ""
}

function _create() {
	# Validate
	case $2 in
		--help|-h)
			_createUsage
			exit 0
		;;
	esac
	# no params provided
	# identity already exists

	# Confirm
	echo -e "${YELLOW}identity${RESET} > ${GREEN}create${RESET}"
	echo -e ""
	echo -e "Creating new identity"
	echo -e "   USERNAME:   $2"
	echo -e "   EMAIL:      $3"
	echo -e ""
	echo -e "Looks ok? (Y/n)"
	echo -e ""
	echo -e "Identity created"
	exit 0
}

# Parse Inputs
case $1 in
	--help|-h)
		_default ;;
	list)
		_list ;;
	create)
		_create $@ ;;
	ssh)
		_ssh $@ ;;
	*)
		_default ; exit 0 ;;
esac

