#!/bin/bash

# To get keyboard id just run `xinput`

function _keyboard() {
  # Set layout for the default keyboard.
  local standard=$(xinput --list --id-only 'keyboard:AT Translated Set 2 keyboard')
  setxkbmap -device $standard -layout "hopkeyboard"

  # Set layout for Logitech keyboard.
  local logi=$(xinput --list --id-only 'keyboard:Logitech MX Keys')
  setxkbmap -device $logi -layout "hopkeyboard+hopkeyboard(swap_lalt_lctl_lwin)"

  # Fix the issue with key repeating
  # https://www.reddit.com/r/archlinux/comments/96rpvu/remapped_keys_via_xmodmap_and_xkb_not_repeating
  xset r on
  xset r 22
  xset r 116
  seq 111 116 | xargs -n 1 xset r
  echo -e "[\033[32mDONE\033[0m] Logitech layout set"
}

function _off() {
  dconf write /org/gnome/desktop/interface/text-scaling-factor "1.4"
  setxkbmap -layout "hopkeyboard"
  echo -e "[\033[32mDONE\033[0m] Logitech turned OFF"
}

function _small() {
  dconf write /org/gnome/desktop/interface/text-scaling-factor "1.2"
  echo -e "[\033[32mDONE\033[0m] Scaling factor set to 1.2"
}

case $1 in
  small)      _small      ; exit 0 ;;
  off)        _off        ; exit 0 ;;
  *)          _keyboard   ; exit 0 ;;
esac
